### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [YuanLiou/TaiwanEbookSearch#116]
as mlkit is not FLOSS

ref: https://github.com/YuanLiou/TaiwanEbookSearch/commit/69b56b74e1226a115a5ae38b52b5a0cac01a1c04#diff-405e612b84deb1f0f7bb69b70c525e621eb0346a4a3e12f12b7f34ed843a5527R18

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/98646aa671cf7144df00f5ab91d86a90f62ab314

**Comment by YuanLiou** [comment]
Hi this project will use `MLKit` in the future. This issue may not fix.
Please use 2.1.2 on F-Droid

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/836d44986ebf082879fd067c16f112d8d2a7e7d4

**Comment by linsui** [comment]
@YuanLiou Looks like the barcode scanning is not a core feature. Can we remove it in F-Droid build?

**Comment by YuanLiou** [comment]
Sure
