### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by linsui** [YuanLiou/TaiwanEbookSearch#42]
Could you please publish this app on F-Droid? Thanks!

**Comment by YuanLiou** [comment]
Hi I'll do a research on how to publish to F-Droid, thanks for the suggestion.

**Comment by linsui** [comment]
Thanks! If you want, I can do that for you.

**Comment by linsui** [comment]
@YuanLiou Can I package it for F-Droid?

**Comment by YuanLiou** [comment]
Hi, sorry for the waiting.

I'm quite busy in this time, yeah you can publish this app to F-Droid

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
I checked the code and found that Firebase and GMS is used. Could I patch them out?

**Comment by YuanLiou** [comment]
Yes

**Comment by linsui** [comment]
The build failed with an error. https://gitlab.com/linsui/fdroiddata/-/jobs/2639568976 Any idea?

**Comment by YuanLiou** [comment]
It shows a (no error message) error 😅

**Comment by linsui** [comment]
OK, it's just an OOM error... I opened an MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11413. Could you please upload your gradle.properties file so that I can just use the properties there? Could I add some metadata in your repo so that F-Droid can fetch app descriptions? Could you please write the version code somewhere so that I can build an apk with the same version code? Thanks!

**Comment by YuanLiou** [comment]
Hi, I think you're gonna needs just HOST and HOST_STAGING right?

What's the key you gonna sign?

**Comment by linsui** [comment]
We sign the apk manully on a air-gap machine. Currently I need to add these lines into gradle.properties:

```
android.useAndroidX=true
android.enableJetifier=true
HOST="https://ebook.yuer.tw/v1/"
HOST_STAGING="https://ebook.yuer.tw/v1/"
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError
```

The build failed with the above error without the last line.

**Comment by YuanLiou** [comment]
OK, got it. The only thing we need is version code right?

I use a script in `buildSrc`, can you trigger it to get one?

it calls `VersionExtension.kt`

**Comment by linsui** [comment]
I can do that but our update checker can't run code. And the result changes on since it get the time stamp.

**Comment by YuanLiou** [comment]
Hi @linsui, can you manually set the version code to `1922012821`?

This will be the same as the Google Play release.

**Comment by linsui** [comment]
Yes, that's what I do. But then we can't update it automatically. At least I need to know that there is an update.

**Comment by YuanLiou** [comment]
Hi @linsui, pull the latest version and try. You'll need add some information into 

`local.properties` to build successfully.

**Comment by linsui** [comment]
Thanks! I'll try ASAP.

**Comment by linsui** [comment]
It works! Thanks! I'll open a PR for the description tomorrow.

**Comment by linsui** [comment]
Kindly ping. Is the PR good to go?

**Comment by YuanLiou** [comment]
Hi @linsui, PR looks good. I'm going to merge and close this issue. Thanks.

**Comment by linsui** [comment]
Thanks! It will be available in F-Droid in 2-3 days.

**Comment by YuanLiou** [comment]
Hi @linsui thank you for the hard working to publish TW Ebook search on F-droid.

Really appreciate.
